### ISSUE TITLE
Could not  open config file

### ISSUE THREAD

**Issue by AdamMiltonBarker** [ipartola/hawkeye#10]
Hi I have followed the installation for RPI 3 and when running I get the error:

Could not open config file: No such file or directory

I have tried sudo and without sudo

**Comment by ipartola** [comment]
There does seem to be an issue here where you have to either specify a config file location explicitly, or have one in the default location. I'll work on a fix, but in the meantime, just create a config file or copy one from the documentation directory, and run it that way.

When you say you installed it on RPI 3, did you build it from scratch or did you install the pre-built package?

**Comment by AdamMiltonBarker** [comment]
I followed the instructions on the home page of this repo for Raspian, no not from scratch mate. I used another library, can close this if you like, sorry forgot to update.

**Comment by ipartola** [comment]
Let's keep this open so I can fix the actual bug with the config file, but I'm glad you got what you needed working.

**Comment by AdamMiltonBarker** [comment]
No problem, glad it was helpful to you also.

**Comment by Obliterous** [comment]
I'm having issues with this bug, building on a Pine64. I've installed the conf file to the default location,  but no joy. How do you specify the config from the command line?
