### ISSUE TITLE
Address:8000 Refused to connect

### ISSUE THREAD

**Issue by DevParapalli** [ipartola/hawkeye#16]

**Comment by aslily1234** [comment]
try to set host to 0.0.0.0 in /opt/webcam_streamer/conf 

If you want to listen on all interfaces try ::0 or 0.0.0.0  
If you want to listen on all interfaces try ::0 or 0.0.0.0
If you want to listen on all interfaces try ::0 or 0.0.0.0

![image](https://user-images.githubusercontent.com/8610207/100047557-b4772a00-2e4d-11eb-926e-e1d6c56dfc87.png)

**Comment by ipartola** [comment]
As mentioned, by default it only listens on the loopback interface. If you want to open it up to the network you need to edit the hawkeye.conf file the daemon is using.
