### ISSUE TITLE
segfault with Debian & Logitech C270

### ISSUE THREAD

**Issue by heipei** [ipartola/hawkeye#3]
Hi there,

maybe you can help me debug this problem I've been having. I'm getting a segfault right after starting hawkeye every time.
OS: Debian Stable (Wheezy)
Kernel: 3.18.1 Vanilla
Hawkeye: git

Backtrace:

```
(gdb) bt
#0  0xb7c9e9df in memcpy () from /lib/i386-linux-gnu/libc.so.6
#1  0x0804bbc6 in copy_frame (dst=dst@entry=0xbff672cc "\377\330\377", <incomplete sequence \340>, 
    dst_size=dst_size@entry=624640, src=0xb797f008 "\377\330\377", <incomplete sequence \340>, 
    src_size=0) at v4l2uvc.c:399
#2  0x0804a366 in grab_frame (fb=0x0) at main.c:122
#3  0x00000000 in ?? ()
```

**Comment by ipartola** [comment]
So sorry, somehow didn't see it until now. Let me see if I can figure out what's up.

**Comment by ipartola** [comment]
OK, sorry it took a while. Try I believe the latest commits fix this. Give it a try (version 0.3 has the latest code), and let me know if it works.
