### ISSUE TITLE
Functions not in use

### ISSUE THREAD

**Issue by davidsilveiro** [ipartola/hawkeye#6]
I'm sure you probably had some either for future features, or perhaps old. Better we dance on the safe side :)

src/memory.c:104       '__wrap_calloc'  
src/memory.c:82         '__wrap_malloc' 
src/memory.c:93         '__wrap_realloc'
src/memory.c:70         '__wrap_strdup' 
src/frames.c:64           'get_current_frame' 
src/main.c:57              'get_real_fps' 
src/memory.c:49         'make_nonce' 
src/profile.c:12            'print_time'
src/memory.c:37         'rng_cleanup'
src/memory.c:32         'rng_init' 
src/v4l2uvc.c:488        'set_resolution' 
src/profile.c:8              'start_time'

**Comment by ipartola** [comment]
I removed the unused functions. Note that __wrap_* functions are actually used: the compiler uses them instead of the corresponding libc functions. For example __wrap_malloc() becomes malloc(). See src/Makefile for details.

**Comment by davidsilveiro** [comment]
Thanks @ipartola ^_^
