### ISSUE TITLE
Request: Option to download JPG snapshot of stream

### ISSUE THREAD

**Issue by ethanpil** [ipartola/hawkeye#8]
I would love to see a feature that allows me to grab a jpg image from a URL and not just watch the stream.

**Comment by ipartola** [comment]
This is not a bad idea. I'll see what I can do.

**Comment by ethanpil** [comment]
Great. I am looking forward to testing this.

**Comment by ipartola** [comment]
Just pushed a new version which allows this. See the update to README.md for how to access the still images.
